### PR TITLE
Remove unnecessary Android-specific stuff

### PR DESCRIPTION
**Pull request by stoyicker**
Begins to address #317 by removing Android manifests which are not doing anything and some unrequired Gradle stuff. Also some Android references in the README have been removed.

However:
* CI runs the check task on the entire project, which means Android is needed for the sample app to work. My recommendation would be that we change the sample to be raw Java, which would allow skipping Android on CI, and therefore make it faster. On top of that, if the artifact is to be changed to be non-Android-specific, it's probably a good idea to not to have the sample not be Android-y anyway. 
* The package name for the most of the code, as well as the maven group id, includes "android" in the name. Both of these should IMHO be refactored out, but I didn't want to take this decision on my own.
* The "commercial effort" (changing Android to Java in things like the repo short-description and tags, and whatever else, is still left to do as that can't be done with a PR

### CODE REVIEW

**Comment by digitalbuddha** [comment]
This seems like the first pr that should work towards next major version  of store. We can change the maven coordinates and remove all the android references. I agree about changing sample project to java.

**Comment by digitalbuddha** [comment]
Give me a bit to get a release plan together and we will merge this in. Thank you for contribution!

**Comment by digitalbuddha** [comment]
could someone on nyt side merge pls

**Review by tiwiz — APPROVED** [review]

**Comment by tiwiz** [comment]
@digitalbuddha I would wait for one more approval before merging it in

**Review by ramonaharrison — APPROVED** [review]

**Pull request merged**
