### PR TITLE
Add FileSystemRecordPersisterFactory

### PR DESCRIPTION
**Pull request by pavlospt**
Add FileSystemRecordPersisterFactory

### CODE REVIEW

**Comment by digitalbuddha** [comment]
I think the Factories are getting a lil out of control. Personally it feels like there should only be 2 Factory classes:
SourcePersisterFactory which can create:
SourcePersister
RecordPersister

FileSystemPersisterFactory which can create:
FileSystemPersister
FileSystemRecordPersister

Mind making those changes good sir?

**Comment by pavlospt** [comment]
@digitalbuddha  Sure, that answers my question on the issue! Let me make the changes and push them :)

**Review by digitalbuddha — APPROVED** [review]

**Comment by digitalbuddha** [comment]
@brianPlummer mind checking over too

**Comment by pavlospt** [comment]
@digitalbuddha Will this be available as a Snapshot when merged?

**Comment by digitalbuddha** [comment]
Yup!

**Review by alexio — APPROVED** [review]

**Comment by pavlospt** [comment]
Thank you for the quick actions!

**Pull request merged**
