### PR TITLE
Add a missing Source.close() call (fixes #196)

### LINKED ISSUE #196: Manual 'close' call missing?
```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

java.lang.Throwable: Explicit termination method 'close' not called

at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at java.io.FileInputStream.<init>(FileInputStream.java:78)
at okio.Okio.source(Okio.java:166)
at com.nytimes.android.external.fs.filesystem.FSFile.source(FSFile.java:82)
at com.nytimes.android.external.fs.filesystem.FileSystemImpl.read(FileSystemImpl.java:54)
at com.nytimes.android.external.fs.FSReader$1.call(FSReader.java:42)
at com.nytimes.android.external.fs.FSReader$1.call(FSReader.java:34)
at rx.internal.operators.OnSubscribeFromEmitter.call(OnSubscribeFromEmitter.java:72)
at rx.internal.operators.OnSubscribeFromEmitter.call(OnSubscribeFromEmitter.java:32)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10144)
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
at rx.Observable.unsafeSubscribe(Observable.java:10144)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10144)
at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
at rx.Observable.unsafeSubscribe(Observable.java:10144)
at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
at rx.Observable.unsafeSubscribe(Observable.java:10144)
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.unsafeSubscribe(Observable.java:10144)
at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:41)
at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
at rx.Subscriber.setProducer(Subscriber.java:211)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
at rx.Subscriber.setProducer(Subscriber.java:205)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
```

Using 2.0.4 with Filesystem and Moshi middleware. I believe this is because `FSReader#read(T key)` should have a `finally` clause that calls `close()` on the `BufferedSource`, but I didn't want to open a PR because I am not 100% sure.

### PR DESCRIPTION
**Pull request by stoyicker**
#196

### CODE REVIEW

**Comment by stoyicker** [comment]
Should I fix the static analysis problems even though they're not related to the pr?

**Comment by digitalbuddha** [comment]
If you don't mind. Weird that they did not come up on last merged pr.

**Comment by stoyicker** [comment]
They didn't exist, it was actually related to my pr, I didn't put anything in the `catch` clause to follow the style in `JacksonSourceParser`, and I forgot to run the check locally, my bad wrt that. I have made it so failing to close now prints the stacktrace to `System.err`, but now the implementation is different than the one in `JacksonSourceParser`, which seems fine in CI terms because the later is not checked by pmd I'm guessing.
There is also a warning from error-prone about a class that could be static but that shouldn't break the build so I don't think I should touch it.

**Review by digitalbuddha — APPROVED** [review]
Thank you for contribution! Will wait for 1 more reviewer to validate

**Review by ramonaharrison — APPROVED** [review]

**Pull request merged**
