### PR TITLE
Remove dead code and add/remove empty lines were needed

### PR DESCRIPTION
**Pull request by pavlospt**
Just some "style" fixes I would say. Still not searched through the entire project, will do over the next days and fix some more if I find.

### CODE REVIEW

**Comment by PaulWoitaschek** [comment]
Btw, what about lambdas in general?

**Comment by pavlospt** [comment]
@PaulWoitaschek Can you explain a bit more ? :)

**Comment by PaulWoitaschek** [comment]
I would love to see lambdas in the source all over the place. Not directly related to your pull request but not that I would open an issue for.

**Comment by digitalbuddha** [comment]
@PaulWoitaschek I wanted to keep adoption as high as possible. There are apps that do not use Retrolambda yet.  Before release I actually had to remove all the lambdas :-(

**Comment by PaulWoitaschek** [comment]
Is it actually an issue for libraries? Don't they get compiled to bytecode targeting JDK6?

**Comment by digitalbuddha** [comment]
I can take a look good thought....

**Pull request merged**
