### PR TITLE
Classnames up, field names down

### PR DESCRIPTION
**Pull request by PaulWoitaschek**
It hurts my eyes ;-)

### CODE REVIEW

**Comment by digitalbuddha** [comment]
Weird that error prone sees errors now. I'll take a look this weekend.

**Comment by PaulWoitaschek** [comment]
I don't get it. You take a look at what?

**Comment by digitalbuddha** [comment]
The error prone issues that are failing build. Or you can fix em. It's failing Travis for a test that can be deleted

**Comment by brianPlummer** [comment]
https://github.com/NYTimes/Store/pull/84 has been merged....a rebase and push should fix this...

**Comment by PaulWoitaschek** [comment]
Like this?

**Pull request merged**
