### PR TITLE
Clear memory store test

### PR DESCRIPTION
**Pull request by PaulWoitaschek**
Wrote a test for clearing the memory.

### CODE REVIEW

**Comment by digitalbuddha** [comment]
We need to clear the no op persister in this case. Seems like your catching all the bugs around having no disk caching.

**Comment by PaulWoitaschek** [comment]
Why did you close it?

**Comment by pavlospt** [comment]
@PaulWoitaschek he moved your test on the other PR that fixes it!

**Comment by digitalbuddha** [comment]
Hey sorry for closing without explanation. Since the pr was on your fork I instead opened another with fix and the test.  I'm retrospect I should have made another pr sans test and then merge yours second. Will do that next time. Thanks again

**Comment by PaulWoitaschek** [comment]
@digitalbuddha Great. Just wanted to make sure that when I make the effort of writing a test it actually ends in the project so it can prevent regressions.

**Comment by digitalbuddha** [comment]
Absoutely. Your effort in writing tests is greatly appreciated.

**Pull request closed without merging**
