### PR TITLE
Avoid multiple resolves of the same Key

### PR DESCRIPTION
**Pull request by pavlospt**
Move resolved Key to a method scoped variable, to avoid trouble, in case `resolve` gets more expensive.

### CODE REVIEW

**Comment by PaulWoitaschek** [comment]
Has a race condition, the whole thing needs to be deferred. See #121

**Comment by pavlospt** [comment]
@PaulWoitaschek Is there any chance that you could rebase your PR over this one, so it would be one PR instead of 2 messing with the same part of code?

**Comment by digitalbuddha** [comment]
already merged the other one, mind rebasing the other direction

**Comment by digitalbuddha** [comment]
sorry I meant just rebase develop

**Comment by pavlospt** [comment]
@digitalbuddha Done, although that automatic commit message from Github Web conflict resolver is kind of strange..

**Comment by PaulWoitaschek** [comment]
Oops sorry I thought I did the single resolve too.

**Pull request merged**
