### PR TITLE
Remove dagger dependency and clean unused dependencies from modules

### PR DESCRIPTION
**Pull request by aminelaadhari**
Fix: Some modules depend on unused dependencies or some dependencies should be testComplie
Remove dagger dependency form modules

### CODE REVIEW

**Comment by digitalbuddha** [comment]
I think we need to make a few changes internally before merging this as we rely on those @Inject annotations on constructors.  Thank you for cleanup! will check and merge later today :-)

**Comment by digitalbuddha** [comment]
Could you leave the inject annotations in. I think those are Jsr and not dagger.

**Comment by aminelaadhari** [comment]
Yes true, I will do that.

**Comment by digitalbuddha** [comment]
Also Pls run check task locally. Looks like some Pmd failures. Otherwise lgtm I'll merge when fixed.

**Comment by aminelaadhari** [comment]
Done. I removed the checkNotNull in Util.createParentDirs because the parameter is annotated with Nonnull. I think the check is not useful anymore.
The pmd was failing because checkNotNull throws a NullPointerException.

**Review by alexio — APPROVED** [review]

**Pull request merged**
